version: '3.5'
services:
  fastapi:
    container_name: fastapi
    image: tiangolo/uvicorn-gunicorn-fastapi:python3.9-slim
    restart: unless-stopped
    # environment:
    ports:
      - 8081:80
    volumes:
       - type: bind
         source: ./backend/app
         target: /app
      #  - ./frontend/...
# volumes:
#   datafile: